Add test scripts for bash and groovy

diff --git a/vsam2/bash/runtests b/vsam2/bash/runtests
--- a/vsam2/bash/runtests
+++ b/vsam2/bash/runtests
@@ -1,13 +1,13 @@
 #!/bin/bash
-
-# runtests: assemble, link  programs and files for zVSAM V2
+# runtests: assemble, link, and run zVSAM V2 tests
+# Optional: tron|troff, then path to z390Archive clone (forwarded to tstload)
 
 ########################################
 # print error message and exit
 ########################################
 
 function errmsg {
-    echo ERROR: $1\; exiting
+    echo "ERROR: $1; exiting"
     exit 8
 }
 
@@ -15,11 +15,11 @@ function errmsg {
 # setup
 ########################################
 
-cd $(dirname $0)     # set to directory of script - z390/vsam2/bash
-cd ../..             # up to z390
+cd "$(dirname "$0")"
+cd ../..
 
 vsampath=vsam2
-zvsam="zvsam(2)"
+zvsam="zVSAM(2)"
 
 ########################################
 # code
@@ -28,23 +28,28 @@ zvsam="zvsam(2)"
 rc=0
 
 # GENCB test
-${vsampath}/bash/testgncb $zvsam
+${vsampath}/bash/testgncb
 rc=$?
 if [ $rc -ne 0 ]; then errmsg "testgncb assembly/link error"; fi
 
 # MODCB test
-${vsampath}/bash/testmdcb $zvsam
+${vsampath}/bash/testmdcb
 rc=$?
 if [ $rc -ne 0 ]; then errmsg "testmdcb assembly/link error"; fi
 
 # SHOWCB test
-${vsampath}/bash/testshcb $zvsam
+${vsampath}/bash/testshcb
 rc=$?
 if [ $rc -ne 0 ]; then errmsg "testshcb assembly/link error"; fi
 
 # TESTCB test
-${vsampath}/bash/testtscb $zvsam
+${vsampath}/bash/testtscb
 rc=$?
 if [ $rc -ne 0 ]; then errmsg "testtscb assembly/link error"; fi
+
+# TSTLOAD suite
+${vsampath}/bash/tstload
+rc=$?
+if [ $rc -ne 0 ]; then errmsg "tstload suite failed"; fi
 
 exit $rc
