Allow bash scripts for assemblies and COBOL compiles to have non-default input file extensions Is662 (#684)
* Allow non-default file extemsions for asm, cblc source input

* Fix typo in runcbldemos

diff --git a/bash/cblcl b/bash/cblcl
--- a/bash/cblcl
+++ b/bash/cblcl
@@ -30,13 +30,31 @@ if [ $trace -eq 1 ]; then set -x; fi
 
 if [ $# -eq 0 ] || [ -z "$1" ]; then echo "cblcl ERROR: missing file name"; exit 16; fi
 
-# remove trailing ".CBL", if any
-zFile="${1%.CBL}"
+# extract longest substring that ends with "/"
+dir=${0%/*}
 
-# error if missing name to left of ".CBL"
-if [ -z "$zFile" ]; then echo "cblcl ERROR: invalid file name $1"; exit 16; fi
-# error if input file with CBL extension does not exist
-if [ ! -f "$zFile".CBL ]; then echo "cblcl ERROR: file $zFile.CBL not found"; exit 16; fi
+# include the file containing the parsefilepath function
+source ${dir}/parsefilepath
+
+# input file path must not end with a period
+if [[ $1 == *. ]]; then echo "cblcl ERROR: file path ends with '.' - $1"; exit 16; fi
+
+# parse file path to get path, name, and extension; sets global variables z_fpath, z_fname, z_fext
+# Examples: if $1="zcobol/demo/HELLO", returned values: z_fpath="zcobol/demo/", z_fname="HELLO" z_fext=""
+#           if $1="zcobol/demo/HELLO.CBL", returned values: z_fpath="zcobol/demo/", z_fname="HELLO" z_fext="CBL"
+parsefilepath "$1"
+if [ $debug -eq 1 ]; then echo "after parsefilepath; \$z_fpath: >$z_fpath<  \$z_fname: >$z_fname<  \$z_fext: >$z_fext<"; fi
+
+# must have z_fname
+if [ -z "$z_fname" ]; then echo "cblcl ERROR: invalid/missing file name in file path- $1"; exit 16; fi
+# must not have a period in z_fname
+if [[ $z_fname == *.* ]]; then echo "cblcl ERROR: invalid character '.' in file name \"$z_fname\"; file path - $1"; exit 16; fi
+# if no z_fext, use default "CBL"
+if [ -z "$z_fext" ]; then z_fext="CBL"; fi
+zFile=${z_fpath}${z_fname}  # path, if any, followed by file name without extension
+# make sure file, with extension, exists
+if [ ! -f ${zFile}.${z_fext} ]; then echo "cblcl ERROR: file $zFile.$z_fext not found"; exit 16; fi
+if [ $debug -eq 1 ]; then echo "full file name with path and extension: >${zFile}.${z_fext}<"; fi
 
 # remove previously created files, if any
 if [ -f "$zFile.MLC" ]; then rm $zFile.MLC; fi
@@ -52,15 +70,13 @@ if [ -f "$zFile.java" ]; then rm $zFile.java; fi
 if [ -f "$zFile.class" ]; then rm $zFile.class; fi
 if [ -f "$zFile_ZC_LABELS.CPY" ]; then rm $zFile._ZC_LABELS.CPY; fi
 
-# extract longest substring that ends with "/"
-dir=${0%/*}
-
 # get the z390 directory
 zdir=$(dirname $0)
 zdir=$(cd $zdir && pwd)
 zdir=$(dirname $zdir)
 
-${dir}/zc390 $zFile $2 $3 $4 $5 $6 $7 $8 $9
+# invoke COBOL preprocessor: convert COBOL source to assembler source (MLC extension)
+${dir}/zc390 $zFile.$z_fext $2 $3 $4 $5 $6 $7 $8 $9
 rc=$?
 if [ $debug -eq 1 ]; then echo "cblcl: zc390 rc=$rc"; fi
 
@@ -72,6 +88,7 @@ if [ $rc -eq 0 ] || [ $rc -eq 4 ]; then
     sysmac='sysmac('$zdir'/zcobol/mac+'$zdir'/mac)'
     syscpy='syscpy(+'$zdir'/zcobol/cpy)'
     if [ $debug -eq 1 ]; then echo "cblcl: cblopt=$cblopt"; fi
+    # invoke macro processor with input the generated assembler source
     ${dir}/mz390 $zFile $cblopt $sysmac $syscpy $2 $3 $4 $5 $6 $7 $8 $9
     rc=$?
     if [ $debug -eq 1 ]; then echo "cblcl: mz390 rc=$rc"; fi
@@ -79,7 +96,8 @@ if [ $rc -eq 0 ] || [ $rc -eq 4 ]; then
     if [ $rc -eq 0 ] || [ $rc -eq 4 ]; then
         if [ $rc -eq 4 ]; then
             echo "cblcl WARNING: mz390 rc=$rc; see warnings in mz390 generated $zFile.BAL/ERR/PRN file(s) and on console"    
-        fi 
+        fi
+        # invoke linker
         ${dir}/lz390 $zFile $2 $3 $4 $5 $6 $7 $8 $9
         rc=$?
         if [ $debug -eq 1 ]; then echo "cblcl: lz390 rc=$rc"; fi
