incorporate changes to corresponding bat files (#445)
Co-authored-by: John Ganci <jganci3@verizon.net>

diff --git a/bash/link b/bash/link
--- a/bash/link
+++ b/bash/link
@@ -5,24 +5,46 @@
 # debug flag; 0=no debug, 1=debug
 debug=0
 
-ECHO=0
-if [ "$1" = "tron" ] || [ "$1" = "TRON" ]; then
-#    echo "setting echo to 1"
-	ECHO=1
-	shift
+rc=0
+trace=0
+
+if [ $# -gt 0 ]; then
+    # save current nocasematch setting
+    SHELLNOCASEMATCH=$(shopt -p nocasematch)
+    shopt -s nocasematch
+    case $1 in
+        "tron")
+            shift
+            trace=1
+            ;;
+        "troff")
+            shift
+            trace=0
+            ;;
+    esac
+    # restore nocasematch setting
+    $SHELLNOCASEMATCH
 fi
 
-if [ -f "$1.390" ]; then rm $1.390; fi
-if [ -f "$1.LST" ]; then rm $1.LST; fi
-if [ -f "$1.ERR" ]; then rm $1.ERR; fi
-if [ -f "$1.STA" ]; then rm $1.STA; fi
-#if [ -f $1.TR* ]; then rm $1.TR*; fi
-shopt -s nullglob
-for f in $1.TR*; do
-#    echo "remove file: $f"
-    if [ -f "$f" ]; then rm "$f"; fi
-done
-shopt -u nullglob
+if [ $trace -eq 1 ]; then set -x; fi
+
+if [ $# -eq 0 ] || [ -z "$1" ]; then echo "link ERROR: missing file name"; exit 16; fi
+# remove trailing ".OBJ", if any
+zFile="${1%.OBJ}"
+
+# error if missing name to left of ".OBJ"
+if [ -z "$zFile" ]; then echo "link ERROR: invalid file name $1"; exit 16; fi
+# error if input file with OBJ extension does not exist
+if [ ! -f "$zFile".MLC ]; then echo "link ERROR: file $zFile.OBJ not found"; exit 16; fi
+
+# remove previously created files, if any
+if [ -f "$zFile.390" ]; then rm $zFile.390; fi
+if [ -f "$zFile.LST" ]; then rm $zFile.LST; fi
+if [ -f "$zFile.ERR" ]; then rm $zFile.ERR; fi
+if [ -f "$zFile.STA" ]; then rm $zFile.STA; fi
+#if [ -f $zFile.TR* ]; then rm $zFile.TR*; fi
+# .TR* file(s) exist if "ls" exit status is 0
+if ls $zFile.TR* 1>/dev/null 2>&1; then rm -f $zFile.TR*; fi
 
 # extract longest substring that ends with "/"
 dir=${0%/*}
@@ -32,12 +54,15 @@ zdir=$(dirname $0)
 zdir=$(cd $zdir && pwd)
 zdir=$(dirname $zdir)
 
-${dir}/lz390 $1 $2 $3 $4 $5 $6 $7 $8 $9
+${dir}/lz390 $zFile $2 $3 $4 $5 $6 $7 $8 $9
 rc=$?
 if [ $debug -eq 1 ]; then echo "link: lz390 rc=$rc"; fi
-if [ "$rc" -ne "0" ]; then
-    echo "link: lz390 error; see errors on lz390 generated $1.LST file and console"
+if [ $rc -ne 0 ]; then
+    if [ $rc -eq 4 ]; then
+        echo "link WARNING: lz390 rc=$rc; see warnings in lz390 generated $zFile.LST file  and on console"
+    else
+        echo "link ERROR: lz390 rc=$rc; see errors in lz390 generated $zFile.LST file and on console"
+    fi
 fi
 
 exit $rc
-
