Add XDECI and XHEXI tests to bash/runassist and bat/RUNASSIST.BAT

diff --git a/bash/runassist b/bash/runassist
--- a/bash/runassist
+++ b/bash/runassist
@@ -25,4 +25,16 @@ rc=$?
 if [ $debug -eq 1 ]; then echo "TESTAST1: rc=$rc"; fi
 if [ "$rc" -ne "0" ]; then echo "Error in TESTAST1"; fi
 
+export XPRNT=assist/test/TSTXDECI.XPR
+bash/asmlg assist/test/TSTXDECI ASSIST 'PARM(v)'
+rc=$?
+if [ $debug -eq 1 ]; then echo "TSTXDECI: rc=$rc"; fi
+if [ "$rc" -ne "0" ]; then echo "Error in TSTXDECI"; fi
+
+export XPRNT=assist/test/TSTXHEXI.XPR
+bash/asmlg assist/test/TSTXHEXI ASSIST 'PARM(v)'
+rc=$?
+if [ $debug -eq 1 ]; then echo "TSTXHEXI: rc=$rc"; fi
+if [ "$rc" -ne "0" ]; then echo "Error in TSTXHEXI"; fi
+
 echo "Verify ASSIST demo and test"
