new version that generates the issue 451 test files

diff --git a/bash/runcodepagetests b/bash/runcodepagetests
--- a/bash/runcodepagetests
+++ b/bash/runcodepagetests
@@ -10,16 +10,82 @@
 #                   3. no scraggly lines in SNAP output of all 256 EBCDIC chars
 #                   4. non-printable chars replaced by '.' in PRN, BAL, PCH
 
-set -e              # exit on all errors
+# debug flag; 0=no debug, 1=debug
+debug=1
+
 cd $(dirname $0)    # set to directory of script
-cd ..
+cd ..               # up one directory; the z390 directory
 
-bash/asml tests/T1P#451 bal $1 $2 $3 $4 $5 $6 $7 $8 $9
-bash/asml tests/T1#451 bal $1 $2 $3 $4 $5 $6 $7 $8 $9
+codepagedir=tests/codepage         # tests/codepage
+javadir=${codepagedir}/java        # tests/codepage/java
+workdir=${codepagedir}/mlcwork     # tests/codepage/mlcwork
+javapgm=CreateIssue451TestFiles    # java program name
 
-bash/exec tests/T1#451 $1 $2 $3 $4 $5 $6 $7 $8 $9
+mkdir -p ${workdir}                # create work directory if it does not exist
 
-echo "Verify tests/T1P#451.BAL and tests/T1#451 look okay"
-echo "Verify console SNAP output does not contain scraggly lines"
+pwd
+echo "javadir=${javadir}"
+echo "workdir=${workdir}"
+echo "javapgm=${javapgm}.java"
 
-exit 0
+compile="y"
+if [ $# -gt 0 ] && [ "$1" = "-nc" ]; then compile=n; shift; fi
+
+if [ $debug -eq 1 ]; then echo "compile=$compile"; fi
+
+if [ $compile = "y" ]; then
+    if [ $debug -eq 1 ]; then echo "Compile program that creates test files ..."; fi
+    javac ${javadir}/${javapgm}.java
+    rc=$?
+    if [ $debug -eq 1 ]; then echo "javac rc=$rc"; fi
+    if [ $rc -ne 0 ]; then
+        echo "Error compiling ${javapgm}.java; rc=$rc"
+        exit $rc
+    fi
+else
+    if [ $debug -eq 1 ]; then echo "Skip compile"; fi
+    if [ ! -f ${javadir}/${javapgm}.class ]; then
+        echo "WARNING: skipping compile but ${javapgm}.class file does not exist"
+    fi
+fi
+
+# empty work directory and copy skeleton file to it
+rm -f ${workdir}/*
+cp ${javadir}/T1#451.MLC.SKEL ${workdir}
+
+if [ $debug -eq 1 ]; then echo "Create test program and data ..."; fi
+# create T1#451.CPY, T1#451.DAT, T1#451.MLC and T1P#451.MLC
+java -cp ${javadir} ${javapgm} ${workdir}
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Error creating test files; rc=$rc"
+    exit $rc
+fi
+
+set -e              # exit on all errors
+
+if [ $debug -eq 1 ]; then echo "Run codepage tests ... "; fi
+
+# build PUNCH load module and test program load module
+bash/asml ${workdir}/T1P#451 bal $1 $2 $3 $4 $5
+bash/asml ${workdir}/T1#451 bal $1 $2 $3 $4 $5
+
+# run the test program
+bash/exec ${workdir}/T1#451 $1 $2 $3 $4 $5
+
+# get number of SNAP output lines that match search criteria
+x=$(grep '^ 00.\{62\}\*$' ${workdir}/T1#451.LOG | wc -l)
+
+if [ $debug -eq 1 ]; then echo "after grep x=$x"; fi
+# if all 16 lines of SNAP output have same length and end with "*"
+if [ $x -eq 16 ]; then
+    echo "No scraggly lines in the SNAP output"
+    rc=0
+else
+    echo "Error: There are scraggly lines in the SNAP output"
+    rc=8
+fi
+
+echo "Verify ${workdir}/T1P#451.BAL and ${workdir}/T1#451.BAL look okay"
+
+exit $rc
